# Generated by Django 3.2.9 on 2021-11-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('imagem', models.FileField(upload_to='')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'RecursosImagem',
                'db_table': 'imagens',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecursoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('video', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'RecursosVideo',
                'db_table': 'videos',
                'managed': True,
            },
        ),
    ]
