# Generated by Django 3.2.9 on 2021-11-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default=None, upload_to='images')),
                ('content', models.TextField(default='')),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'ImageResources',
                'db_table': 'images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('video', models.FileField(default=None, upload_to='videos')),
                ('content', models.TextField(default='')),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'VideoResources',
                'db_table': 'videos',
                'managed': True,
            },
        ),
    ]
