# Generated by Django 3.2.9 on 2021-11-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursovideo',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recursoimagem',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recursoimagem',
            name='imagem',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recursovideo',
            name='video',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
