# Generated by Django 3.2.9 on 2021-11-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211120_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursoimagem',
            name='imagem',
            field=models.ImageField(default=None, upload_to='imagens'),
        ),
        migrations.AlterField(
            model_name='recursovideo',
            name='video',
            field=models.FileField(default=None, upload_to='videos'),
        ),
    ]
