# Generated by Django 3.2.9 on 2021-11-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211120_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursoimagem',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recursovideo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
